/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrmTristone;

import Entities.EmployeeEntity;
import Entities.ProductsEntity;
import Entities.StationEntity;
import Model.EmployeesModel;
import Model.ProductModel;
import Model.StationModel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ulises
 */
public class frmScanProduct extends javax.swing.JFrame {

    public String _idEmployee;
    /**
     * Creates new form frmScanProduct
     */
    public frmScanProduct() {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
        
        //getEmployee(_idEmployee);
        jtxtMessage.setEditable(false);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtNoSAP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlblEmployeeName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblEmployeeNumb = new javax.swing.JLabel();
        jtxtMessage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Name:");
        jLabel1.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee ID:");

        jtxtNoSAP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtxtNoSAP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNoSAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNoSAPKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SAP Number");

        jlblEmployeeName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblEmployeeName.setForeground(new java.awt.Color(255, 255, 255));
        jlblEmployeeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblEmployeeName.setText("Employee Name:");
        jlblEmployeeName.setName("jlblEmployee"); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tristone.png"))); // NOI18N

        jlblEmployeeNumb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblEmployeeNumb.setForeground(new java.awt.Color(255, 255, 255));
        jlblEmployeeNumb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblEmployeeNumb.setText("Employee Number:");
        jlblEmployeeNumb.setName("jlblEmployee"); // NOI18N

        jtxtMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtxtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblEmployeeNumb, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jlblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNoSAP, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jtxtMessage)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtNoSAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblEmployeeName)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblEmployeeNumb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jtxtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jlblNameTittle");
        jLabel2.getAccessibleContext().setAccessibleName("jlblName");
        jLabel3.getAccessibleContext().setAccessibleName("jlblEmployeeNum");
        jLabel4.getAccessibleContext().setAccessibleName("jlblemployeeNumbertxt");
        jtxtNoSAP.getAccessibleContext().setAccessibleName("jtxtSapNumber");
        jLabel5.getAccessibleContext().setAccessibleName("jlblSAPNum");
        jlblEmployeeName.getAccessibleContext().setAccessibleName("jlblEmployee");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNoSAPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNoSAPKeyPressed
        // TODO add your handling code here:
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
            String noSAP = jtxtNoSAP.getText();
            if(GetData(noSAP)){
                
            }else
            {
                jtxtMessage.setText("Invalid Number");
                jtxtMessage.setBackground(Color.red);                
                jtxtMessage.setEditable(false);
                jtxtNoSAP.setText("");
                ReseteBox();
            }
            
//            if(GetData(noSAP)){
//                //JOptionPane.showConfirmDialog(null,"Excelente");
//                frmStandarPAck _frmStandardPack = new frmStandarPAck();
//                _frmStandardPack.SetEmployee(_idEmployee);
//                _frmStandardPack.SetNoSAP(noSAP);
//                _frmStandardPack.setVisible(true);
//                this.setVisible(false);
//                this.dispose();
//            }
                
            
        }
    }//GEN-LAST:event_jtxtNoSAPKeyPressed
    
    private boolean GetBartender(String dbName,String noSAP){
        boolean result = false;
         boolean COM = false;
        ProductsEntity _productEntity=new ProductsEntity();
        StationModel objStationModel =new StationModel();
        ArrayList<Object> listTable=new ArrayList<Object>();
        listTable = objStationModel.GetTableName(dbName);
        
        if(listTable.size() > 0){
            for(Object o : listTable){
                result= objStationModel.ValidateBartender(o.toString(), noSAP,dbName);
                if(result == true){
                     
                    _productEntity = objStationModel.GetDataProduct(o.toString(), noSAP,dbName);
                    
//                    
                    try {
                        if(COM){
                                frmDigitalScale _frmDigitalScale = new frmDigitalScale();
                                _frmDigitalScale.SetEmployee(_idEmployee);
                                _frmDigitalScale.SetNoSAP(_productEntity);
                                _frmDigitalScale.setVisible(true);
                                this.dispose();
                        } else{
                                frmStandarPAck _frmStandardPack = new frmStandarPAck();
                                _frmStandardPack.SetEmployee(_idEmployee);
                                _frmStandardPack.initialize();
                                _frmStandardPack.SetNoSAP(_productEntity);
                                _frmStandardPack.setVisible(true);
                                this.dispose();
                        }
                        
                        
                    
                    } catch (Exception e) {
                        JOptionPane.showConfirmDialog(null, ""+ e.getMessage(), "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                    }finally{
                        //this.setVisible(false);
                        //this.dispose();
                        //break;
                    }
//                   
                }
            }
        }
        
        return result;
    }
    
    private void ReseteBox(){
       Timer timer;
       TimerTask task;
       int time=2000;
       task = new TimerTask() {
           @Override
           public void run() {
               jtxtMessage.setText("");
                jtxtMessage.setBackground(Color.white);                
                jtxtMessage.setEditable(false);
           }
       };
       
       timer =new Timer();
       timer.schedule(task, time);
       
   }
    
    private boolean GetData(String noSAP){
        
        boolean result=false;
         String dbPath="";
        String dbName = "";
        String userDB="";
        String passDB="";
        String station="";
        String passApp="";
        String scanSleep="";
        String company="";
        //String serialPort="";
        
        String _cancelCode = "";
        StationEntity _stationEntity = new StationEntity();
        StationModel objStationModel =new StationModel();
        String path=new File ("TristonePath.txt").getAbsolutePath ();
                      
        File file = new File(path);
        try{
                if(file.exists())
                {
                    Scanner sc = new Scanner(file); 

                    dbPath = sc.nextLine();
                    dbName = sc.nextLine();
                    userDB = sc.nextLine();
                    passDB = sc.nextLine();
                    station = sc.nextLine();
                    company = sc.nextLine();
                    passApp = sc.nextLine();
                    scanSleep = sc.nextLine();
                    
                    //serialPort = sc.nextLine();
                    
                    
                    _stationEntity = objStationModel.getStationConf(station);
                    result=GetBartender(_stationEntity.getMysql_db() ,noSAP);
                }
                else{
                    jtxtMessage.setText("The File doesn't exist"); 
                    jtxtMessage.setBackground(Color.red);
                    jtxtMessage.setEditable(false);
                    ReseteBox();
                }
                
        }
        catch (Exception e) {
            e.printStackTrace();
            return result;
        }
        finally{
            return result;    
        }
    }
    
    private boolean ExistNoSAP(String noSAP){
        boolean _existNoSAP = false;
        ProductModel objProductModel =new ProductModel();
        _existNoSAP = objProductModel.ProductExist(noSAP);
        if(_existNoSAP)
            _existNoSAP = GetData(noSAP);
        return _existNoSAP;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmScanProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmScanProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmScanProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmScanProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmScanProduct().setVisible(true);                
            }
            
        });
    }
    
    public void getEmployee(String idEmployee)
    {
        EmployeesModel objEmployee=new EmployeesModel();
        EmployeeEntity _employeeEntity=new EmployeeEntity();
        _employeeEntity = objEmployee.getEmployee(idEmployee);
                
        jlblEmployeeName.setText(_employeeEntity.getNameEmployee());
        jlblEmployeeNumb.setText(_employeeEntity.getNumEmployee());
        _idEmployee = _employeeEntity.getIdEmployee();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlblEmployeeName;
    private javax.swing.JLabel jlblEmployeeNumb;
    private javax.swing.JTextField jtxtMessage;
    private javax.swing.JTextField jtxtNoSAP;
    // End of variables declaration//GEN-END:variables
}
